project_id = "fizryssrfsojiavxmhrt"

[functions]
  [functions.admin-api]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.generate-banner]
    verify_jwt = false
  [functions.generate-landing]
    verify_jwt = false
  [functions.mercadopago-webhook]
    verify_jwt = false
  [functions.send-payment-email]
    verify_jwt = false
  [functions.send-campaign-email]
    verify_jwt = false
  [functions.check-plan-expiration]
    verify_jwt = false
  [functions.process-automations]
    verify_jwt = false
  [functions.shopify-export]
    verify_jwt = false
  [functions.shopify-oauth-callback]
    verify_jwt = false
  [functions.generate-dropi-ads]
    verify_jwt = false
