project_id = "fizryssrfsojiavxmhrt"

[functions.generate-landing]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.generate-banner]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false
